# Generated by Django 2.2.6 on 2019-11-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_name', models.CharField(max_length=60)),
                ('art_description', models.TextField()),
                ('art_image', models.ImageField(upload_to='art/')),
                ('art_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Category')),
                ('art_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Location')),
            ],
        ),
    ]
