# Generated by Django 2.2.6 on 2019-11-11 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'ordering': ['art_name']},
        ),
    ]
